# **Import the Required Library**

In [2]:
import numpy as np

 **Q1. Write a Numpy program to get the Numpy version.**

In [3]:
import numpy as np

# Get the NumPy version
print(np.__version__)


1.23.5


**Q2. Write a NumPy program to test whether none of the
elements of a given array are zero.**

In [4]:

# Test array
test_array = np.array([1, 2, 3, 4, 5])

# Check if none of the elements are zero
none_zero = np.all(test_array != 0)

print("None of the elements are zero:", none_zero)

# Test array with a zero element
test_array_with_zero = np.array([1, 2, 0, 4, 5])

# Check if none of the elements are zero
none_zero_with_zero = np.all(test_array_with_zero != 0)

print("None of the elements are zero:", none_zero_with_zero)


None of the elements are zero: True
None of the elements are zero: False


**Q3.Write a NumPy program to create an element-wise
comparison (greater, greater_equal, less and less_equal) of
two given arrays.**

In [5]:

# Create two arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([2, 2, 3, 3, 4])

# Element-wise comparison
greater_than = array1 > array2
greater_equal = array1 >= array2
less_than = array1 < array2
less_equal = array1 <= array2

# Print the results
print("Array1 > Array2:", greater_than)
print("Array1 >= Array2:", greater_equal)
print("Array1 < Array2:", less_than)
print("Array1 <= Array2:", less_equal)


Array1 > Array2: [False False False  True  True]
Array1 >= Array2: [False  True  True  True  True]
Array1 < Array2: [ True False False False False]
Array1 <= Array2: [ True  True  True False False]


**Q4. Write a NumPy program to create an array with the values
1, 7, 13, 105 and determine the size of the memory occupied
by the array.**

In [6]:

# Create the array
arr = np.array([1, 7, 13, 105])

# Determine the size of the memory occupied by the array
memory_size_bytes = arr.nbytes

print("Array:", arr)
print("Memory size occupied by the array:", memory_size_bytes, "bytes")


Array: [  1   7  13 105]
Memory size occupied by the array: 32 bytes


**Q5. Write a NumPy program to create an array of integers
from 30 to 70.**

In [7]:

# Create an array of integers from 30 to 70
arr = np.arange(30, 71)

print("Array of integers from 30 to 70:", arr)


Array of integers from 30 to 70: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


**Q7.  Write a NumPy program to create a 3x3 identity matrix.
Write a search NumPy program to create a 3X4 array and
iterate over it.**

In [8]:

# Creating a 3x3 identity matrix
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:")
print(identity_matrix)

# Creating a 3x4 array
array_3x4 = np.array([[1, 2, 3, 4],
                       [5, 6, 7, 8],
                       [9, 10, 11, 12]])

print("\n3x4 Array:")
print(array_3x4)

# Iterating over the 3x4 array
print("\nIterating over the 3x4 array:")
for row in array_3x4:
    for element in row:
        print(element, end=" ")
    print()


3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

3x4 Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Iterating over the 3x4 array:
1 2 3 4 
5 6 7 8 
9 10 11 12 


**or**

In [9]:

# Creating a 3x3 identity matrix
identity_matrix = np.identity(3)
print("3x3 Identity Matrix:")
print(identity_matrix)

# Creating a 3x4 array
array_3x4 = np.arange(1, 13).reshape(3, 4)
print("\n3x4 Array:")
print(array_3x4)

# Iterating over the 3x4 array
print("\nIterating over the 3x4 array:")
for row in array_3x4:
    for element in row:
        print(element, end=" ")
    print()


3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

3x4 Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Iterating over the 3x4 array:
1 2 3 4 
5 6 7 8 
9 10 11 12 
